import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/Navbar";
import {Footer} from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/586b261bcd.js"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body className={inter.className}>
        <div className="flex min-h-screen flex-col bg-[#121212]">
          <Navbar />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
